<?php

class WorkerFive
{
    public $color;
    public $square;
    const SIDES_COUNT = null;

    public function infoAbout()
    {
        echo "Это геометрическая фигура! ";
    }
}

class Rectangle extends WorkerFive
{
    private $a, $b;
    const SIDES_COUNT = 4;

    public function __construct($a, $b)
    {
        $this->a = $a;
        $this->b = $b;
    }

    public function getArea()
    {
        echo "Площадь равна: S = {$this->a} * {$this->b} = " . $this->square = $this->a * $this->b . '<br>';
    }

    public function infoAbout()
    {
        parent::infoAbout(); // TODO: Change the autogenerated stub
        echo 'Это класс прямоугольника. У него ' . self::SIDES_COUNT . ' стороны. ';
    }
}

class Triangle extends WorkerFive
{
    private $a, $b, $c;
    const SIDES_COUNT = 3;

    public function __construct($a, $b, $c)
    {
        $this->a = $a;
        $this->b = $b;
        $this->c = $c;
    }

    public function getArea()
    {
        echo "Площадь равна: S = {$this->a} * {$this->b} * {$this->c} = " . $this->square = $this->a * $this->b * $this->c . '<br>';
    }

    public function infoAbout()
    {
        parent::infoAbout(); // TODO: Change the autogenerated stub
        echo 'Это класс треугольника. У него ' . self::SIDES_COUNT . ' стороны. ';
    }
}

class Square extends WorkerFive
{
    private $a;
    const SIDES_COUNT = 4;

    public function __construct($a)
    {
        $this->a = $a;
    }

    public function getArea()
    {
        echo "Площадь равна: S = {$this->a} * {$this->a} = " . $this->square = pow($this->a, 2) . '<br>';
    }

    public function infoAbout()
    {
        parent::infoAbout(); // TODO: Change the autogenerated stub
        echo 'Это класс квадрата. У него ' . self::SIDES_COUNT . ' стороны. ';
    }

}